### ISSUE TITLE
For You ignores blocking and muting

### ISSUE THREAD

**Issue by jobukkit** [TheBLVD/mammoth#127] opened 2023-08-28 12:41 UTC
**Describe the bug**

I have both blocked and muted `@NPR@press.coop`, but it continues to appear in For You.

**To Reproduce**

1. Block or mute an account in the For You feed
2. It will continue to appear in the future.

**Expected behavior**

I expect to not see an account again after blocking or muting it.

**Screenshots**

![IMG_E338446F645D-1](https://github.com/TheBLVD/mammoth/assets/2750434/f16893e7-5d5d-47ed-95e5-035b2b772f65)
![IMG_0808](https://github.com/TheBLVD/mammoth/assets/2750434/c2514c9b-7e06-4453-aa2b-66da5049eff7)

**Smartphone (please complete the following information):**
 - Version: 1.10.2

**Comment by FabrizioMusacchio** [comment] 2023-09-01 21:23
(build 261) Same issue for me. Blocking or muting users has no (permanent) effect. As soon as the blocked users post new posts, they reappear in the For You feed.

**Comment by bvon** [comment] 2023-12-20 19:36
This appears to be working as intended in Mammoth 2. I've blocked/muted a few Business News accounts, which no longer appear.

Also tested a few moments ago, and it's working well. Closing ticket.

**Closed by bvon** 2023-12-20 19:36 UTC
Labels: bug
