### ISSUE TITLE
Searching for a specific profile URL brought me to the wrong profile

### ISSUE THREAD

**Issue by mikix** [TheBLVD/mammoth#94] opened 2023-04-30 04:39 UTC
**Describe the bug**
I pasted one url into the search bar, pressed “Search” and got brought immediately to a profile I didn’t expect.

**To Reproduce**
1. Go to explore tab
2. Search for `https://weirder.earth/@s`
3. See the profile of `@stephenfry@mastodonapp.uk` come up (maybe that’s specific to me, I dunno)

**Expected behavior**
Search results that might match what I searched for. Or no search results. But def not a profile page.

**Screenshots**

https://user-images.githubusercontent.com/1196901/235335674-2d375fd5-5793-41a6-b11e-74f51f1886f7.mp4

**Smartphone (please complete the following information):**
 - Device: iPhone 11 
 - OS: iOS 16.4.1
 - Version: 153

**Additional context**
I was originally posting an actual valid profile url (unlike @s) and it brought me to a different, but also wrong url. But since I didn’t want to put that person’s profile on blast, I changed the url and it still brought me to the wrong place. I did keep the same hostname of weirder.earth

**Comment by dchansen42** [comment] 2023-04-30 14:36
I can confirm that this issue, though slightly different manifestation, happened to me on April 17th and I also have a screen recording of it. When prepping the recording for upload to this ticket however, I noticed that the errant profile it jumps to is slightly NSFW (No visible posts that I can see, just the profile picture itself and possibly the translation of the name.). Please advise on whether or not you want me to upload this.
The way this issue manifested for me is that I was scrolling through my following feed, saw an interesting post, selected the post and then wanted to look at the poster's profile and was directed to some completely unrelated account on a different instance. I went back and repeated it. I then went all the way back to my following feed and select the profile icon directly and went to the correct profile. Rinsed and repeated enough to see that the problem was stable and then did a screen recording showing the issue.

The errant account also seems to exhibit the problem noted in ticket #93. The recording shows that the errant profile is ~5 years old and on that day displayed that it had 1 post (Though you do not see any posts.) and was labeled "today" as the last post. I went to it a few minutes ago and the app displays the same information, still labeled as having a single post and that it was posted "today".

**Comment by NathanRLiu** [comment] 2023-04-30 18:09
Nice find! I got taken to SportCenter's page; my guess is it disregards everything up until the @, when i tried doing the same thing for a new york times bot it took me to a nyt bot that was on a different instance.

**Comment by bvon** [comment] 2023-12-18 20:45
Appears to be addressed in Mammoth 2 (MAM-1509)

**Closed by bvon** 2023-12-18 20:45 UTC
Labels: bug
