### ISSUE TITLE
Link abbreviating breaks on file extensions

### ISSUE THREAD

**Issue by mikix** [TheBLVD/mammoth#95] opened 2023-05-01 01:43 UTC
**Describe the bug**
I’ve noticed that some links are broken, seemingly because of a file extension like .html being treated as a sentence break

**To Reproduce**
1. Send yourself a private message with a long link with an extension like (just a random article where I noticed this): https://www.miamiherald.com/detour/article274840151.html
2. Open the message and click on the link

**Expected behavior**
File extensions not breaking a link

**Screenshots**
<img width="414" alt="image" src="https://user-images.githubusercontent.com/1196901/235388607-3f355635-0ef0-484a-a2d0-905e51dfcd53.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 16.4.1
 - Version 153

**Additional context**

**Comment by NathanRLiu** [comment] 2023-05-06 23:15
Hey there! This issue was caused by a regression from us trying to fix a previous bug when the RegEx for link detection would include trailing periods (I love www.google.com.) We're gonna do some digging and see if we can try and get the best of both worlds.

**Comment by bvon** [comment] 2023-12-18 20:54
Resolved in Mammoth 2

**Closed by bvon** 2023-12-18 20:54 UTC
Labels: bug
