### ISSUE TITLE
Posting photos in iPad doesn't work

### ISSUE THREAD

**Issue by richardbrockie** [TheBLVD/mammoth#25] opened 2023-02-25 20:30 UTC
Hi,

For a long time the betas, and now the release, for **iPadOS** has a bug when writing a toot. Trying to either use the camera or choose a picture from my photo library does nothing. Mammoth has access to the Camera in Settings as it definitely was working with an early beta. I'm using an iPad mini 5th gen currently running iPadOS 16.3.1.

Everything works ok on my up to date iPhone 11 Pro.

**Comment by pjolt** [comment] 2023-02-25 21:30
I can replicate the issue when trying to take a picture in the compose window with the camera button in left bottom on Mammoth. It takes the picture and processes it (loading circle) but then it shows attracted screen. A small white line can be seen in the ui, towards top right. But no UI buttons etc and only way out is to force close app. It almost feels like there is some change in resolution in the window after upload completes that causes this almost blown out view. 

No issue uploading from library. 
iPad Air M1, iOS 16.3.1. Mammoth 1.0.2 Build 114. 

![image](https://user-images.githubusercontent.com/120338442/221380431-8acd37d9-fa12-49d0-997f-38c26676aaa0.png)

**Comment by ShihabM** [comment] 2023-02-28 09:42
Thanks for this, we will work on resolving this soon.

**Comment by MissPurrple** [comment] 2023-06-27 08:43
Hey @richardbrockie & @pjolt 💜 Thank you for reporting the above issues.
In the latest version of Mammoth which is now available on the Apple Store, you should be able to easily add a photo from your library or capture one to post directly. We think the issue is fully fixed now and should not show up again; if however you still come across it or it’s variation at any point, please let us know and we will get right on it! For now, I will close this issue filing. 🦣

**Closed by MissPurrple** 2023-06-27 08:43 UTC
Labels: bug
