### ISSUE TITLE
Ability to use other activity pub services

### ISSUE THREAD

**Issue by turbo-vision** [TheBLVD/mammoth#40] opened 2023-03-01 04:46 UTC
**Is your feature request related to a problem? Please describe.**
I can login to accounts that use other activity pub services but can’t view any content

**Describe the solution you'd like**
Support for other activity pub services

**Describe alternatives you've considered**
I’ve tried many different apps but the well designed ones don’t support different activity pub services and the ones that do are half baked with bad UX.

**Comment by pjolt** [comment] 2023-03-01 05:29
Duplicate of #27

**Comment by sdubinsky** [comment] 2023-03-01 13:11
This is on our roadmap, we'll get there soon!  Is there a specific service you'd like to use with Mammoth?

**Comment by turbo-vision** [comment] 2023-03-02 21:00
> This is on our roadmap, we'll get there soon! Is there a specific service you'd like to use with Mammoth?

Pleroma is the only other one I can really think of!

**Comment by turbo-vision** [comment] 2023-03-07 04:09
> This is on our roadmap, we'll get there soon! Is there a specific service you'd like to use with Mammoth?

I’ve since learned that Rebased is another backend that some of my communities use, which is a fork of Pleroma.

**Comment by bvon** [comment] 2023-12-18 18:54
Appears to be resolved in Mammoth 2 [MAM-2993]

**Closed by bvon** 2023-12-18 18:54 UTC
Labels: Feature request
