### ISSUE TITLE
Offcenter loading indicators on iPad

### ISSUE THREAD

**Issue by TGRush** [TheBLVD/mammoth#102] opened 2023-05-23 11:41 UTC
**Describe the bug**
The loading indicator in some views of the app (e.g loading trending posts) is not centered within the column, and appears too far on the right or not at all (depending on the column width set in the settings)

**To Reproduce**
1. Open Mammoth on any iPad
2. Enter any page / column which has a loading spinner
3. See the bug.

**Expected behavior**
I expect the loading spinner/indicator to be centered within the column.

**Screenshots**
![80FBE906-A796-4CD4-822E-26BBE2953E9F](https://github.com/TheBLVD/mammoth/assets/58338843/707bff9f-f65b-4673-a4f1-d345f0c022da)

**Smartphone (please complete the following information):**
 - Device: iPad Air 2
 - OS: iOS 15.7.1
 - Version 1.6 Build 175

**Additional context**
I believe that the position of the loading indicator might be based on screen width, or another value which is unrelated to the column‘s width.

**Comment by NathanRLiu** [comment] 2023-05-27 18:09
Hey! Filed this in the bug tracker a few days ago but forgot to respond to you & let you know. Thanks for submitting!

**Comment by MissPurrple** [comment] 2023-06-27 08:33
Hey @TGRush 💜 Thank you for reporting the above issue.
In the latest version of Mammoth which is now available on the Apple Store, the loading spinner should no long be off centre. We think the issue is fully fixed now and should not show up again; if however you still come across it at any point, please let us know and we will get right on it! For now, I will close this issue filing. 🦣

**Closed by MissPurrple** 2023-06-27 08:33 UTC
Labels: bug
