### ISSUE TITLE
Make iPad Left Nav Items Follow Column Sequence from Settings

### ISSUE THREAD

**Issue by ScottCFrancis** [TheBLVD/mammoth#32] opened 2023-02-27 00:48 UTC
**Is your feature request related to a problem? Please describe.**
When I rearrange the Column order in Settings, the updated order isn't reflected in the Left Nav, which is disorienting. 

**Describe the solution you'd like**
Make the Left Nav items follow the Column sequence configured in Settings. 

**Describe alternatives you've considered**
* Not being bothered by the inconsistency. This hasn't been working out for me. 
* Closing my eyes and hoping really hard the Left Nav sequence will just, through the force of my will and positive energy, change to match Settings. Also not working (at least so far). I will keep trying. 
* Saying, "Please change now" to the screen. Like, very politely. Also...nothing. 

**Additional context**
Please see the attached screenshot. 

<img width="712" alt="image" src="https://user-images.githubusercontent.com/44330350/221448151-aa0fa4de-b89c-4544-a783-a0a2e252039a.png">

**Comment by ShihabM** [comment] 2023-02-28 09:46
Great catch, thanks for this!

**Comment by MissPurrple** [comment] 2023-06-27 08:37
Hey @ScottCFrancis 💜 Thank you for reporting the above issue.
In the latest version of Mammoth which is now available on the Apple Store, the overall layout has been changed so the column issue should no longer exist. We think the issue is fully fixed now and should not show up again; if however you still come across it or it’s variation at any point, please let us know and we will get right on it! For now, I will close this issue filing. 🦣

**Closed by MissPurrple** 2023-06-27 08:37 UTC
Labels: Feature request
