### ISSUE TITLE
Scroll snap

### ISSUE THREAD

**Issue by morganwdavis** [TheBLVD/mammoth#83] opened 2023-04-10 19:48 UTC
**Is your feature request related to a problem? Please describe.**
Most scrolling on a touch device (e.g. iPad) is vertical but any horizontal deviation will move the horizontal scroll position.  It’s not difficult to get partial column clipping on the left side because of this.

**Describe the solution you'd like**
I’d like to see CSS-like scroll snapping support so that you can always maintain horizontal alignment and not get columns cut off, yet still have the ability to do horizontal column scrolling.

**Describe alternatives you've considered**
N/a

**Additional context**
It’s easy to repro or visual to see the effect

**Comment by NathanRLiu** [comment] 2023-04-12 23:50
Hi Morgan! Thanks for the feature request. More than happy to file a ticket but would you mind attaching a visual aid to help us diagnose the issue?

**Comment by morganwdavis** [comment] 2023-04-14 03:12
Here’s what it looks like on iPad if you the horizontal positions shifts just a little. You can cut the profile images off, even though you’re just a few pixels away from having them show if scroll snap was enabled.  (Or whatever the equivalent of that is in native — presumably Swift? — app development.  If that’s not a feature you’re familiar with, see MDN’s page on CSS scroll snapping).CSS Scroll Snap - CSS: Cascading Style Sheets | MDNdeveloper.mozilla.org--MorganOn Apr 12, 2023, at 4:51 PM, NathanRLiu ***@***.***> wrote:﻿
Hi Morgan! Thanks for the feature request. More than happy to file a ticket but would you mind attaching a visual aid to help us diagnose the issue?

**Comment by MissPurrple** [comment] 2023-06-27 08:55
Hey @morganwdavis 💜 Thank you for reporting the above issues.
In the latest version of Mammoth which is now available on the Apple Store, the overall layout has been changed so you should no longer have issues with the horizontal scroll snap as there not much need to scroll horizontally if any at all. We think the issue is fully fixed now and should not show up again; if however you still come across it or it’s variation at any point, please let us know and we will get right on it! For now, I will close this issue filing. 🦣

**Closed by MissPurrple** 2023-06-27 08:55 UTC
Labels: Feature request
