### ISSUE TITLE
Mastondon Custom Emojis Either Invisible or Disappearing in Posts

### ISSUE THREAD

**Issue by JoesBrat67** [TheBLVD/mammoth#66] opened 2023-03-14 01:11 UTC
I've noticed on Mammoth v1.2 build 128 on iPhone 13 Pro Max - when custom emojis are added to a post, any animation associated with the emoji does not work.  The emoji can be seen in the post in the list view, but when displaying just the full post, the emoji becomes invisible.
![IMG_4211](https://user-images.githubusercontent.com/127805798/224866732-efcc5f80-5efc-4b3d-98f2-ed24279ea060.PNG)

In other instances, the custom emoji does not appear at all.
![IMG_4210](https://user-images.githubusercontent.com/127805798/224866747-da363c9b-8b06-4f17-b
![IMG_4209](https://user-images.githubusercontent.com/127805798/224866752-110584ce-5952-49fc-a068-535f1ff087a0.PNG)
![IMG_4208](https://user-images.githubusercontent.com/127805798/224866755-b1b9dc63-4a04-4de9-866c-0197c5142136.PNG)

65b-29afce4b1b5d.PNG)

**Comment by sdubinsky** [comment] 2023-03-16 10:16
dupe of https://github.com/TheBLVD/mammoth/issues/60, I think.  We're working on a fix!

**Comment by derspyy** [comment] 2024-01-27 21:54
live since 2.4 : )

**Closed** 2024-01-30 02:20 UTC
Labels: bug
